MVCWebApp/Controllers/MissingPeopleController.cs
using MVCApp.Data.Models;
using MVCApp.Data.Services;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MVCWebApp.Controllers
{
    public class MissingPeopleController : Controller
    {
        private readonly IMissingPeoplesData db;

        public MissingPeopleController(IMissingPeoplesData db)
        {
            this.db = db;
        }

        [HttpGet]
        public ActionResult Index(string sortOrder, string currentFilter, string searchStr, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NSortParm = String.IsNullOrEmpty(sortOrder) ? "First_Name_desc" : "";
            ViewBag.LSortParm = sortOrder == "L_Name" ? "Last_Name_desc" : "L_Name";


            if (searchStr != null)
            {
                page = 1;
            }
            else
            {
                searchStr = currentFilter;
            }

            ViewBag.CurrentFilter = searchStr;

            var peoples = from p in db.GetAll()
                          select p;

            if (!String.IsNullOrEmpty(searchStr))
            {
                peoples = peoples.Where(s => s.FirstName.ToUpper().Contains(searchStr.ToUpper())
                                       || s.LastName.ToUpper().Contains(searchStr.ToUpper()));
            }

            switch (sortOrder)
            {
                case "First_Name_desc":
                    peoples = peoples.OrderByDescending(s => s.FirstName);
                    break;
                case "L_Name":
                    peoples = peoples.OrderBy(s => s.LastName);
                    break;
                case "Last_Name_desc":
                    peoples = peoples.OrderByDescending(s => s.LastName);
                    break;
                default:
                    peoples = peoples.OrderBy(s => s.FirstName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(peoples.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = db.Get(id);
            if(model == null)
            {
                return View("NotFound");
            }
            return View(model);
        } 

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MissingPeoples missingPeoples)
        {
            //if (String.IsNullOrEmpty(missingPeoples.FirstName))
            //{
            //    ModelState.AddModelError(nameof(missingPeoples.FirstName), "First Name is required!");
            //}

            //if (String.IsNullOrEmpty(missingPeoples.LastName))
            //{
            //    ModelState.AddModelError(nameof(missingPeoples.LastName), "Last Name is required!");
            //}

            if (ModelState.IsValid)
            {
                db.Add(missingPeoples);
                return RedirectToAction("Details", new { id = missingPeoples.Id });
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Edit(int id)
        {
            var model = db.Get(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Edit(MissingPeoples missingPeoples)
        {
            if (ModelState.IsValid)
            {
                db.Update(missingPeoples);
                TempData["Message"] = "You have succesfully saved the data!";
                return RedirectToAction("Details", new { id = missingPeoples.Id });
            }
            return View(missingPeoples);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Delete(int id)
        {
            var model = db.Get(id);
            if(model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Delete(int id, FormCollection form)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MVCWebApp/Controllers/RoleController.cs
using MVCApp.Data.Models;
using MVCApp.Data.Services;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;

namespace MVCWebApp.Controllers
{
    public class RoleController : Controller
    {
        private readonly IAspNetUsersData db;

        public RoleController(IAspNetUsersData db)
        {
            this.db = db;
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Index(string sortOrder, string currentFilter, string searchStr, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NSortParm = String.IsNullOrEmpty(sortOrder) ? "First_Name_desc" : "";
            ViewBag.LSortParm = sortOrder == "L_Name" ? "Last_Name_desc" : "L_Name";

            if (searchStr != null)
            {
                page = 1;
            }
            else
            {
                searchStr = currentFilter;
            }

            ViewBag.CurrentFilter = searchStr;

            var users = from p in db.GetAll()
                          select p;

            if (!String.IsNullOrEmpty(searchStr))
            {
                users = users.Where(s => s.UserName.ToUpper().Contains(searchStr.ToUpper())
                                       || s.Email.ToUpper().Contains(searchStr.ToUpper()));
            }

            switch (sortOrder)
            {
                case "First_Name_desc":
                    users = users.OrderByDescending(s => s.UserName);
                    break;
                case "L_Name":
                    users = users.OrderBy(s => s.Email);
                    break;
                case "Last_Name_desc":
                    users = users.OrderByDescending(s => s.UserName);
                    break;
                default:
                    users = users.OrderBy(s => s.Email);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(users.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Details(string id)
        {
            var model = db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Edit(string id)
        {
            var model = db.Get(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Edit(UserData users)
        {
            if (ModelState.IsValid)
            {
                db.Update(users);
                TempData["Message"] = "You have succesfully saved the data!";
                return RedirectToAction("Details", new { id = users.Id });
            }
            return View(users);
        }
    }
}

MVCWebApp/Views/Shared/_Layout.cshtml
@*@model System.Attribute*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>@ViewBag.Title - My ASP.NET Application</title>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Missing People", "Index", "MissingPeople")</li>
                    <li>@Html.ActionLink("Roles", "Index", "Role")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if(TempData["Message"] != null)
        {
            <div class="alert alert-info">
                @TempData["Message"]
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>